### ISSUE TITLE
Can you please add some screenshots as mentioned in [contribution guidelines](https://github.com/iiitl/moviedb/blob/master/CONTRIBUTING.md) showing the visual change - the favicon in this case?

### ISSUE THREAD

**Issue by monarkjain** [iiitl/moviedb#32]
![favicon](https://user-images.githubusercontent.com/123642419/216879085-5ea30234-c03b-4749-9213-95e0f86ba268.png)
              Can you please add some screenshots as mentioned in [contribution guidelines](https://github.com/iiitl/moviedb/blob/master/CONTRIBUTING.md) showing the visual change - the favicon in this case?

_Originally posted by @chakri68 in https://github.com/iiitl/moviedb/issues/25#issuecomment-1418434868_

**Comment by chakri68** [comment]
This is for your PR. Not the repo as a whole.
